#!/usr/bin/env bash
# Regenerate syntaxes/zshrs.tmLanguage.json from the zshrs binary's own
# reflection tables, so the grammar carries the COMPLETE language surface
# (every builtin, extension, and special variable) and never drifts. Run
# after a zshrs upgrade.
#
#   ./scripts/gen_grammar.sh            # uses `zshrs` on $PATH
#   ZSHRS=/path/to/zshrs ./scripts/gen_grammar.sh
#
# Source of truth (the binary, not a hand-maintained list):
#   zshrs --dump-reflection   # JSON: .builtins .extensions .special_vars .keywords
#
# Partitioning:
#   extensions   -> their OWN scope (support.function.extension.zshrs); these are
#                   the zshrs world-first additions. Every extension is also a key
#                   in .builtins, so it must be removed from the plain builtin set.
#   builtins     -> .builtins keys MINUS keyword names MINUS extension names.
#   special_vars -> variable.language.zshrs
# Keywords are static (control + declaration) — see the grammar repository below.
set -euo pipefail

zshrs="${ZSHRS:-zshrs}"
here="$(cd "$(dirname "$0")/.." && pwd)"
out="$here/syntaxes/zshrs.tmLanguage.json"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

ident='^[A-Za-z_][A-Za-z0-9_]*$'

"$zshrs" --dump-reflection > "$tmp/refl.json"
ver="$("$zshrs" --version 2>/dev/null | grep -oE 'v?[0-9]+\.[0-9]+\.[0-9]+' | head -1)"

jq -r '.builtins|keys[]'      "$tmp/refl.json" | grep -E "$ident" | sort -u > "$tmp/b.txt"
jq -r '.extensions|keys[]'    "$tmp/refl.json" | grep -E "$ident" | sort -u > "$tmp/e.txt"
jq -r '.special_vars|keys[]'  "$tmp/refl.json" | grep -E "$ident" | sort -u > "$tmp/s.txt"
jq -r '.keywords|keys[]'      "$tmp/refl.json" | grep -E "$ident" | sort -u > "$tmp/k.txt"

# Plain builtins = .builtins keys minus keyword names minus extension names.
comm -23 "$tmp/b.txt" "$tmp/k.txt" | comm -23 - "$tmp/e.txt" > "$tmp/plain.txt"

# Longest-first so the alternation never matches a prefix of a longer name.
alt() { awk '{ print length, $0 }' "$1" | sort -rn -k1,1 -k2 | cut -d' ' -f2- | paste -sd'|' -; }
BUILTIN_RE="$(alt "$tmp/plain.txt")"
EXTENSION_RE="$(alt "$tmp/e.txt")"
SPECIALVAR_RE="$(alt "$tmp/s.txt")"

nb="$(wc -l < "$tmp/plain.txt" | tr -d ' ')"
ne="$(wc -l < "$tmp/e.txt" | tr -d ' ')"
ns="$(wc -l < "$tmp/s.txt" | tr -d ' ')"

jq -n \
  --arg builtins "$BUILTIN_RE" \
  --arg extensions "$EXTENSION_RE" \
  --arg specialvars "$SPECIALVAR_RE" \
  --arg version "${ver:-unknown}" \
  --arg nbuiltins "$nb" \
  --arg nextensions "$ne" \
  --arg nspecialvars "$ns" '
{
  "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  "name": "zshrs",
  "scopeName": "source.zshrs",
  "fileTypes": ["zsh", "zshenv", "zprofile", "zlogin", "zlogout", "zsh-theme", "zshrc"],
  "_generated": ("GENERATED by scripts/gen_grammar.sh from the zshrs binary (--dump-reflection) — zshrs " + $version + ", " + $nbuiltins + " builtins, " + $nextensions + " extensions, " + $nspecialvars + " special vars. Do not edit by hand."),
  "patterns": [
    { "include": "#shebang" },
    { "include": "#comments" },
    { "include": "#strings" },
    { "include": "#heredoc" },
    { "include": "#numbers" },
    { "include": "#keywords-control" },
    { "include": "#keywords-decl" },
    { "include": "#extensions" },
    { "include": "#builtins" },
    { "include": "#special-vars" },
    { "include": "#command-substitution" },
    { "include": "#variables" },
    { "include": "#operators" }
  ],
  "repository": {
    "shebang": {
      "match": "\\A#!.*$",
      "name": "comment.line.shebang.zshrs"
    },
    "comments": {
      "match": "(^|\\s)#.*$",
      "name": "comment.line.number-sign.zshrs"
    },
    "numbers": {
      "match": "\\b(0x[0-9A-Fa-f]+|0b[01]+|0o?[0-7]+|\\d[\\d_]*\\.\\d[\\d_]*([eE][-+]?\\d+)?|\\d[\\d_]*([eE][-+]?\\d+)?)\\b",
      "name": "constant.numeric.zshrs"
    },
    "variables": {
      "patterns": [
        { "match": "\\$#?[A-Za-z_]\\w*", "name": "variable.other.zshrs" },
        { "match": "\\$\\{[^}]*\\}", "name": "variable.other.bracket.zshrs" },
        { "match": "\\$[0-9]", "name": "variable.language.positional.zshrs" },
        { "match": "\\$[@*#?$!-]", "name": "variable.language.special.zshrs" }
      ]
    },
    "special-vars": {
      "match": ("\\b(?:" + $specialvars + ")\\b"),
      "name": "variable.language.zshrs"
    },
    "command-substitution": {
      "patterns": [
        {
          "name": "string.interpolated.dollar.zshrs",
          "begin": "\\$\\(", "end": "\\)",
          "patterns": [ { "include": "$self" } ]
        }
      ]
    },
    "strings": {
      "patterns": [
        {
          "name": "string.quoted.double.zshrs",
          "begin": "\"", "end": "\"",
          "patterns": [
            { "match": "\\\\.", "name": "constant.character.escape.zshrs" },
            { "match": "\\$\\{[^}]*\\}|\\$#?[A-Za-z_]\\w*|\\$[@*#?$!0-9-]", "name": "variable.other.interpolated.zshrs" }
          ]
        },
        {
          "name": "string.quoted.single.zshrs",
          "begin": "'"'"'", "end": "'"'"'"
        },
        {
          "name": "string.interpolated.backtick.zshrs",
          "begin": "`", "end": "`",
          "patterns": [
            { "match": "\\\\.", "name": "constant.character.escape.zshrs" },
            { "match": "\\$\\{[^}]*\\}|\\$#?[A-Za-z_]\\w*", "name": "variable.other.interpolated.zshrs" }
          ]
        }
      ]
    },
    "heredoc": {
      "begin": "<<-?[\"'"'"']?([A-Za-z_]\\w*)[\"'"'"']?",
      "beginCaptures": { "0": { "name": "keyword.operator.heredoc.zshrs" } },
      "end": "^\\s*\\1\\b",
      "name": "string.unquoted.heredoc.zshrs",
      "patterns": [
        { "match": "\\$\\{[^}]*\\}|\\$#?[A-Za-z_]\\w*", "name": "variable.other.interpolated.zshrs" }
      ]
    },
    "keywords-control": {
      "match": "\\b(case|do|done|elif|else|end|esac|fi|for|foreach|if|in|repeat|select|then|until|while|function|break|continue|exit|logout|return)\\b",
      "name": "keyword.control.zshrs"
    },
    "keywords-decl": {
      "match": "\\b(declare|export|float|integer|let|local|readonly|set|shift|typeset)\\b",
      "name": "storage.modifier.zshrs"
    },
    "extensions": {
      "match": ("\\b(?:" + $extensions + ")\\b"),
      "name": "support.function.extension.zshrs"
    },
    "builtins": {
      "match": ("\\b(?:" + $builtins + ")\\b"),
      "name": "support.function.builtin.zshrs"
    },
    "operators": {
      "patterns": [
        { "name": "keyword.operator.pipe.zshrs", "match": "\\|&?|&&|;;|;" },
        { "name": "keyword.operator.redirect.zshrs", "match": "&?>>?|<<?|>&|<&|[0-9]+>&?" },
        { "name": "keyword.operator.zshrs", "match": "=~|==|!=|<=|>=|=|!|&" }
      ]
    }
  }
}
' > "$out"

echo "wrote $out ($(wc -c < "$out" | tr -d ' ') bytes; $nb builtins, $ne extensions, $ns special vars; zshrs ${ver:-unknown})"
